import unittest
import os
import sys

# Add backend directory to sys.path so modules resolve correctly
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "backend"))

class TestGate1Exif(unittest.TestCase):
  """
  Tests the Gate 1 EXIF signature analysis decisions.
  """
  def test_authentic_camera_tag_matches(self):
    # Simulated authentic tags (Make in known_camera_makes, GPS present)
    make = "Apple"
    has_gps = True
    has_iso = True
    
    known_camera_makes = [
      "Apple", "Samsung", "Google", "Sony", "Canon", "Nikon", 
      "Fujifilm", "DJI", "GoPro", "Huawei", "OnePlus", "Xiaomi", 
      "OPPO", "Realme", "Motorola", "Nokia", "Vivo"
    ]
    
    score = 0.0
    if make in known_camera_makes:
      score += 0.35
    if has_gps:
      score += 0.15
    if has_iso:
      score += 0.10
      
    self.assertEqual(score, 0.60)
    self.assertTrue(score > 0.30)

  def test_ai_generator_tag_rejection(self):
    # Software metadata containing AI generator keyword
    software_tag = "Generated by Stable Diffusion v1.5"
    ai_keywords = ["Stable Diffusion", "DALL-E", "Midjourney", "Gemini", "Adobe Firefly"]
    
    is_fake = any(kw in software_tag for kw in ai_keywords)
    self.assertTrue(is_fake)

  def test_scrubbed_metadata_anomalies(self):
    # WhatsApp or Telegram scrubbed headers
    software = None
    make = None
    
    is_suspicious = (software is None) and (make is None)
    self.assertTrue(is_suspicious)

if __name__ == "__main__":
  unittest.main()
